/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_5_1: THREE.Mesh
    Object_5_2: THREE.Mesh
  }
  materials: {
    FRAME_7: THREE.MeshStandardMaterial
    PHOTO_5: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5_1.geometry}
          material={materials.FRAME_7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5_2.geometry}
          material={materials.PHOTO_5}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
